version: '3.8'

services:
  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "61616:61616"  # Porta para conexões de mensagens (JMS)
      - "8161:8161"    # Porta para a interface web do ActiveMQ
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    networks:
      - apache-camel-with-spring-boot
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - apache-camel-with-spring-boot
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - apache-camel-with-spring-boot
networks:
  apache-camel-with-spring-boot:
    driver: bridge
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local